### PR TITLE
Added option to test reading the glTF sample models

### PR DESCRIPTION
**Pull request by javagl**
This PR is (probably) not supposed to be merged so soon. 

It contains some infrastructure for doing a batch-run and try to read the glTF sample models from the [glTF-Sample-Models repo](https://github.com/KhronosGroup/glTF-Sample-Models) using the `CesiumGltfReader`. 

It reads the `model-index.json` file from the sample models repo, which contains information about the available sample models and their variants (plain, embedded, binary, draco), and stores that info as some

	vector{ name, vector{ variantName, variantFileName } }

structure. These `SampleModel` objects can then be processed further. (E.g they could be filtered based on the variant or name - right now, the `variantsToTest` includes all variants)

The current process is that the test simply tries to load the models, and reports when there is any error while doing so.

This is wrapped into a test, as of https://github.com/CesiumGS/cesium-native/compare/gltf-sample-models-read-test#diff-326bf15b729481bb3ceb378fd5463b179c0d85b400a26512257be82e4566f980R6 , **but** this is not a sensible "unit test", of course: It takes quite a while to read all models, and the question of *where* the models should be read from remains open. 

(Right now, they are read from a local file, with the path essentially being hard-wired in the test case. The option to extend this to read the models from the repo exists, but would require adding some `libcurl` or so, and that would be *really* slow...)

This test originally was only intended as a basic litmus test/validation for the reader. Whether or not this (or parts of this) will become "real" tests can be decided later.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @javagl! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @javagl! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by javagl** [comment]
Thank you, cesium-concierge 👍 

I appreciate the bumps, but obviously, the work that has been done in this PR is not aligned with the overall priorities. The code in this PR is largely part of a standalone project called `cesium-cpp`, which uses `cesium-native` and contains various "integration-level tests" and utilities. Right now, this is a _private_ project, but I'll consider to clean it up and make it _public_ after your next notification.

**Comment by javagl** [comment]
Yeah, it's not forgotton. Maybe after the next bump 🙄

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @javagl! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by javagl** [comment]
So here we go: https://github.com/javagl/cesium-cpp - nothing important to see there, but now made public in order to finally wrap this up....

**Pull request closed without merging**
