### PR TITLE
Fix logical errors in byteStride calculations

### PR DESCRIPTION
**Pull request by Yeah-Zi**
Fixed loading failure issue when byteStride  description is 0 in buffer view

### CODE REVIEW

**Comment by kring** [comment]
@Yeah-Zi can you explain more why this is needed? If a `bufferView` has `byteStride` explicitly specified to be zero, that's a broken glTF. The value is _required_ to be greater than or equal to 4:
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_bufferview_bytestride

**Comment by Yeah-Zi** [comment]
Thank you for providing the standard format specification for gltf.
Why I need this is because the customer provides data with a byteStride of 0, it can be loaded normally in CesiumJS, while Cesium For Unreal cannot

**Comment by Yeah-Zi** [comment]
@kring Perhaps some log information can be added here, as loading failure does not result in any errors. It took me some time to debug this error

**Comment by Yeah-Zi** [comment]
i found how cesiumjs due with this situation:
https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Scene/GltfPipeline/getAccessorByteStride.js

**Comment by kring** [comment]
> Perhaps some log information can be added here, as loading failure does not result in any errors.

I'm not opposed to adding some more logging but, in general, cesium-native is a loader, not a validator. A proper glTF validator (like this one: https://github.khronos.org/glTF-Validator/) should easily detect invalid glTF files like this.

However, in this case, since your change matches what CesiumJS is already doing, and it has very little cost, I'm happy to merge it. Can you please sign the Contributor License Agreement first:
https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

Thank you for the PR!

**Comment by Yeah-Zi** [comment]
@kring I have signed the CLA

**Comment by kring** [comment]
Thanks @Yeah-Zi!

**Pull request merged**
