### PR TITLE
Raster Overlays on 3d Tiles

### PR DESCRIPTION
**Pull request by kring**
This builds on #326 and adds the ability to use raster overlaps (including for clipping) on 3D Tiles instead of just on terrain.

### CODE REVIEW

**Comment by kring** [comment]
This is back in a usable state now, but there are some problems:
* [ ] RTC_CENTER and a non-standard glTF up axis are not accounted for when computing texture coordinates, making them totally wrong.
* [ ] A leaf tile with a geometric error of 0.0 can have an arbitrary number of the deepest-level raster overlay tiles mapped to it. That can go very badly.
* [ ] Computing a GlobeRectangle from a bounding volume doesn't produce very good results in some cases. It would be much better to compute the projected Rectangle from the tile's vertices.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @kring! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by xuelongmu** [comment]
Not urgent at all because I'm not using cesium-native on Android at the moment, but wanted to let you know about a couple compilation errors I'm getting when building cesium-unreal on Android using this branch of cesium-native:

```
../cesium-native/Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp:383:45: error: implicit conversion changes signedness: 'int32_t' (aka 'int') to 'std::__ndk1::vector<CesiumGeometry::Rectangle, std::__ndk1::allocator<CesiumGeometry::Rectangle> >::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const Rectangle& rectangle = rectangles[index];
                                 ~~~~~~~~~~ ^~~~~
../cesium-native/Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp:451:51: error: implicit conversion changes signedness: 'int32_t' (aka 'int') to 'std::__ndk1::vector<CesiumGeometry::Rectangle, std::__ndk1::allocator<CesiumGeometry::Rectangle> >::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
  const Rectangle& geometryRectangle = rectangles[projectionIndex];
                                       ~~~~~~~~~~ ^~~~~~~~~~~~~~~
../cesium-native/Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp:447:23: error: comparison of integers of different signs: 'int32_t' (aka 'int') and 'std::__ndk1::vector<CesiumGeometry::Rectangle, std::__ndk1::allocator<CesiumGeometry::Rectangle> >::size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
  if (projectionIndex >= rectangles.size()) {
```

**Comment by kring** [comment]
Thanks @xuelongmu, should be fixed now. This branch is still in active development though.

**Comment by kring** [comment]
ok! This is finally ready! I still need to do a little work on the Unreal side to make the raster overlay SSE configurable, but that doesn't need to hold up this PR.

A few fun screen shots:

Cesium OSM Buildings with Bing draped on it. You can clearly see the low-res textures on bigger buildings because of the ADD refinement, but it still looks pretty cool:
image

Here's Denver with and without a Bing overlay:
denver

And here I've clipped out the MCG and replaced it with a spiffy pool, just to make everyone in Melbourne mad at me:
image

(pool model from here: https://www.turbosquid.com/3d-models/3d-model-water-fountain-1387533)

**Comment by nithinp7** [comment]
Thanks @kring, this is awesome, it brings some new life to OSM buildings and other low-detail tilesets to be able to drape imagery on top! The code looks very good from what I've read through. I think it's ready to merge after the small merge conflicts I fixed above. I'll merge the Unreal side to this as well after it passes CI.

**Pull request merged**
