### PR TITLE
Fixed the issue where the Y-axis tile coordinates could not be correctly calculated after customizing the root tile slicing scheme

### PR DESCRIPTION
**Pull request by sailra**

### CODE REVIEW

**Comment by kring** [comment]
Thanks for the PR @sailra! Before we review and merge this, can you please sign the Contributor License Agreement:
https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by sailra** [comment]
OK, I signed.

**Comment by kring** [comment]
Thanks @sailra! I'm going to merge this and then update CHANGES.md in main.

**Comment by kring** [comment]
https://github.com/CesiumGS/cesium-native/commit/d36e59883e93be4cb05a08beabd7a854f85dfc52

**Pull request merged**
