### PR TITLE
Don't always report zero-length images as errors.

### PR DESCRIPTION
**Pull request by kring**
`BingMapsRasterOverlay` purposely requests that the Bing servers return a zero-length image for non-existent tiles. That's what the `n=z` query parameter does. So we shouldn't report these zero-length images as a problem.

### CODE REVIEW

**Comment by kring** [comment]
> remove incorrect move

If I'm not mistaken, those moves are valid because the lambda is marked mutable. So the lambda gets a copy, and then the copy is moved into the result.

**Comment by baothientran** [comment]
I just googled it and it caught me surprised. If `const ref` is captured by lambda like this `[option]() mutable {}` , the option type is `const` too even the lambda is mutable. It was mentioned here https://stackoverflow.com/questions/31485041/lambda-capture-by-value-mutable-doesnt-work-with-const.

I tried it out and it is indeed const in the lambda too:
https://godbolt.org/z/dTzsKffGT

**Comment by kring** [comment]
C++ is silly. 😆 
Ok so the problem is that the captured variable is const to begin with, so it gets captured as const even though it's also copied. We don't need to remove the `std::move` though, we just need to capture it differently. Like this: https://godbolt.org/z/P9ojG9ET6

Right?

**Comment by baothientran** [comment]
Yup that's right lol

**Comment by baothientran** [comment]
@kring can you please review the move again? Other than that, everything else looks good to me

**Comment by kring** [comment]
Looks good to me, thanks @baothientran!

**Pull request merged**
