### PR TITLE
First pass of clang tidy

### PR DESCRIPTION
**Pull request by jtorresfabra**
Mainly caching else after return, not using empty() instead of size() == 0, missing const references to avoid copies and removing redundant initializations. 

There are still missing several fixes that I left for following passes if we accept this first one, including:
* Incosistent case style for global constants
* Inconsistent case style for parameters/variables
* Differing parameters names between headers and sources
* Code that may throw exceptions in no-except declared functions
* Following rule of five if rule of zero can't be followed (Up to discussion on how to act on this)

Some of the changes explanation for reference:
https://clang.llvm.org/extra/clang-tidy/checks/performance-move-const-arg.html
https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html
https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html
https://clang.llvm.org/extra/clang-tidy/checks/bugprone-branch-clone.html
https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html
https://clang.llvm.org/extra/clang-tidy/checks/readability-simplify-boolean-expr.html

### CODE REVIEW

**Comment by shehzan10** [comment]
@jtorresfabra How much of this can be made part of clang-format?

**Comment by baothientran** [comment]
@shehzan10 this is C++ linter clang-tidy which I think we should integrate it with cesium-native soon

**Comment by jtorresfabra** [comment]
@shehzan10 as Bao said, it is a different tool, nothing of this can be made part of clang-format AFAIK.

**Comment by shehzan10** [comment]
> @shehzan10 this is C++ linter clang-tidy which I think we should integrate it with cesium-native soon

Yeah I think this was my intention (I forgot that clang has a variety of tools). If we can make this process part of the CI, that would be fantastic.

**Comment by kring** [comment]
Thanks @jtorresfabra! One thing I want to ask you about: member initialization. I noticed you removed a bunch of initializers, I guess because they're redundant. But then some were left in place that I thought also weren't needed, like `Tileset::_pRootTile` (which is a `std::unique_ptr`). My rule of thumb was always just to initialize every member in the order its declared, in order to avoid and surprises. Your rule is probably better, but can you articulate it? And maybe we should put it in the coding guidelines as well.

**Comment by jtorresfabra** [comment]
Hi @kring

> But then some were left in place that I thought also weren't needed, like `Tileset::_pRootTile` (which is a `std::unique_ptr`)

This is only a first pass and clang-tidy is still complaining about a lot more of stuff. So probably it got buried in the big warning logs from clang-tidy I have. To be honest, my rule of thumb was the same as yours before clang-tidy checked for it, these days I just follow https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html to ease readability. 

Say that, this check can be disabled if we don't find comfortable with it, so everything in this PR is up to discussion and we can tweak the clang-tidy rules if we are not happy with them.

**Pull request merged**
