### PR TITLE
Fix libjpeg turbo build for iOS simulator

### PR DESCRIPTION
**Pull request by pjanetzek**
Hello, this change was necessary for our CI build for iOS simulator.

The error was
```
ld: warning: ignoring file ***/cesium-native/extern/libjpeg-turbo/lib/libturbojpeg.a, 
   building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
```

### CODE REVIEW

**Comment by kring** [comment]
Thanks @pjanetzek! Can I bug you to sign the Contributor License Agreement?
https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by pjanetzek** [comment]
Hey Kevin - yes, we got a green light to sign the NDA but it might take few days to figure out some details

**Comment by pjanetzek** [comment]
Hello Kevin - we've sent the signed CLA for our team at Peer. Could you check if you have everything necessary from us?

**Comment by shehzan10** [comment]
@pjanetzek @speedym I can confirm that CLA has been received.

CC @kring

**Comment by kring** [comment]
Thanks @pjanetzek! @joseph-kaile can you please review and merge this?

**Comment by joseph-kaile** [comment]
Hello @pjanetzek, when installing the libjpeg turbo library on Cesium For Unreal, I wasn't able because the $(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME) wasn't getting resolved. I think I found a substitute using CMake variables. If you could test these changes (https://github.com/CesiumGS/cesium-native/commit/26e948546391e2ee37a3c164187fadb9d602bd14), it would be highly appreciated.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @pjanetzek! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Pull request closed without merging**
