### PR TITLE
Use map instead of unordered_map for dictionary properties in CesiumGltf and Cesium3DTiles

### PR DESCRIPTION
**Pull request by lilleyse**
`std::map` will preserve the order of elements in the dictionary so that we don't get different glTF / 3D Tiles serialization results on different compilers.

I first noticed this when working on the 3D Tiles writer where one of the unit tests was failing on windows because the order of "property1" and "property2" happened to be swapped.

```
{
  "asset": {
    "version": "1.0",
    "tilesetVersion": "1.2.3"
  },
  "properties": {
    "property2": {
      "maximum": 5,
      "minimum": 1
    },
    "property1": {
      "maximum": 10,
      "minimum": 0
    }
  },
```

```
{
  "asset": {
    "version": "1.0",
    "tilesetVersion": "1.2.3"
  },
  "properties": {
    "property1": {
      "maximum": 10,
      "minimum": 0
    },
    "property2": {
      "maximum": 5,
      "minimum": 1
    }
  },
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
This PR is now well out of date so I'll close it. But it may come up again in the future.

**Pull request closed without merging**
