### PR TITLE
Install debug vcpkg libraries from `debug/lib`

### PR DESCRIPTION
**Pull request by lilleyse**
Debug vcpkg libraries should be installed from the `debug/lib` directory, not the `lib` directory.

image

### CODE REVIEW

**Comment by kring** [comment]
@lilleyse I'm going to move this out of this week's release just to avoid adding any more risk to the Cesium for Unreal release, which is already a pretty risky one. Let me know if there's any reason I'm not aware of that it does need to ship this month.

**Comment by lilleyse** [comment]
@kring that's fine

**Comment by kring** [comment]
I just tried this out in cesium-unreal, and (perhaps unsurprisingly) it causes linker errors due to mismatched debug / release CRT. This is frustrating because our overlay triplet specifies:

```
set(VCPKG_CXX_FLAGS "/MD /Zp8")
set(VCPKG_C_FLAGS "${VCPKG_CXX_FLAGS}")
```

But it seems that something - perhaps individual libraries - are ignoring or overriding this.

**Comment by kring** [comment]
I believe I have the Unreal issues fixed in https://github.com/CesiumGS/cesium-unreal/pull/1543. Once CI confirms that, I'll merge this. Thanks @lilleyse!

**Pull request merged**
