### PR TITLE
CMake Usability Improvements

### PR DESCRIPTION
**Pull request by josephbirkner**
This PR introduces two small usability improvements with Cesium Native's CMake setup:
* The compile option `CESIUM_GLM_STRICT_ENABLED`, which allows disabling the restrictive GLM compile flags that are set by Cesium Native. In our project, we need the otherwise disabled GLM features.
* Furthermore, the Catch2 dependency is now optional, as it is only included if tests are enabled. In our project, we bring in a newer Catch2 version, and we don't want to build/run the Cesium Native tests.

### CODE REVIEW

**Comment by kring** [comment]
Thank you for the PR @josephbirkner! Can I please ask you to sign the Contributor License Agreement so that we can review and merge this? https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by josephbirkner** [comment]
@kring Thanks for the reminder. Signed!

**Comment by kring** [comment]
Thanks @josephbirkner! This looks good and I'm happy to merge it. But I just noticed that one of the commits in this PR is by @MisterGC. Is it possible for them to sign the CLA as well?

**Comment by kring** [comment]
Thanks @josephbirkner and @MisterGC!

**Pull request merged**
