### PR TITLE
Add a function to load a glTF file

### PR DESCRIPTION
**Pull request by timoore**
The new function GltfReader::loadGltf() loads a glTF file, resolves external data, and does draco decompression if necessary.

This is very useful for implementing a stand-alone glTF viewer and testing the resource preparer code for a cesium-native client. I haven't included any test cases because I don't see a mock accessor that can read from a local file system. For my own testing in vsgCs I use my curl-based accessor with a file: protocol.

### CODE REVIEW

**Comment by kring** [comment]
Thanks for the PR @timoore! Just to be sure I'm understanding, is this necessary because you're testing with models where the Draco buffer is stored externally to the glTF?

**Comment by timoore** [comment]
> Thanks for the PR @timoore! Just to be sure I'm understanding, is this necessary because you're testing with models where the Draco buffer is stored externally to the glTF?

Yes, for example [the duck](https://github.com/KhronosGroup/glTF-Sample-Models/blob/f51daf8d63cdba18ab64c89184f46969dddc0b8b/2.0/Duck/glTF-Draco/Duck.gltf). Alternatively, you could let a client implement this by exporting `CesiumGltfReader::decodeDraco`.

**Comment by kring** [comment]
Right, makes sense. I think a bit more of a restructure might be in order, as other post-processing steps - other than Draco decoding - also fail to happen if they involve external buffers.

**Comment by kring** [comment]
Yeah it's not common in 3D Tiles, because getting the entire tile in one request is more efficient, but it's allowed. It could even be useful in certain cases, like providing uncompressed mesh or texture data in a separate buffer for clients that don't support Draco, KTX2, etc.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by javagl** [comment]
If I understood this correctly, then this fixes https://github.com/CesiumGS/cesium-native/issues/629

> I don't see a mock accessor that can read from a local file system. 

For the tests, it might be possible to solve that with the [`SimpleAssetAccessor`](https://github.com/CesiumGS/cesium-native/blob/4ac2705ce08e11788e636dd2c83d4be6fc146e9d/Cesium3DTilesSelection/test/SimpleAssetAccessor.h). 

But if this is supposed to be part of the (public) core functionality, then it's not that easy. I once created a [`FileAssetAccessor`](https://github.com/javagl/cesium-cpp/blob/4bca6e97c3cd3f567907384f13bc1b36f381bfa1/Source/src/CesiumNativeImpl/FileAssetAccessor.cpp) for some local tests, but ... the fact that all this is entangled with the `AsyncSystem`, which in turn assumes that everything is about network requests, makes this a bit quirky. 

For clients who really just want to _use_ the glTF functionality, there should be a
```
GltfReaderResult result = GltfReader.loadGltf(std::string& uri);
```
function. No `AsyncSystem`. No `Future` 😨 . Just a function to read the glTF model (from the file system). 

The fact that this could internally delegate to some 
```
return "await" this->loadGltf(someDefaultAsyncSystem, AssetAccessors.forFileSystem(uri), ...);
```
call may not have to be visible for clients. One could, however, argue that there should be a `boolean` flag (maybe as a parameter or as part of the `options` like `resolveReferences`, so that users can decide whether they only want the main glTF, or whethere the references should already be resolved.

**Comment by kring** [comment]
Thanks for making further changes @timoore! I'll take a look soon (hopefully tomorrow) and let you know if we can merge it or what else needs to happen. I definitely like the concept, just might need to hammer out some details.

**Comment by javagl** [comment]
Thanks again for your contribution @timoore!

No one has commented on this pull request in a while. Maintainers, can you review, merge or close to keep things tidy?

_I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@javagl stop`. If you want me to start again, just delete the comment._

<sub>(I'm just doing this because it might solve https://github.com/CesiumGS/cesium-native/issues/629 that I opened a while ago...)</sub>

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
This would also be helpful for glTF related unit tests in cesium-omniverse. CC @mattelser

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by javagl** [comment]
I'm curious what would have to happen here to get this merged. I know how difficult it can be to offer a public API, particularly when this is supposed to be built on top of things that are simply not a good fit for the API that is supposed to be offered. But CesiumGltf being a glTF loader library that cannot load glTF files sounds awkward, and we should think about _some_ path for improving this. (Depending on whether timoore is even still tracking this - it has been a while - I could try to allocate some time and either pick up this PR or draft some ideas about how the functionality could be offered...)

**Comment by timoore** [comment]
On Thu, Sep 28, 2023, 1:53 PM Marco Hutter ***@***.***> wrote:

> I'm curious what would have to happen here to get this merged. I know how
> difficult it can be to offer a public API, particularly when this is
> supposed to be built on top of things that are simply not a good fit for
> the API that is supposed to be offered. But CesiumGltf being a glTF loader
> library that cannot load glTF files sounds awkward, and we should think
> about *some* path for improving this. (Depending on whether timoore is
> even still tracking this - it has been a while - I could try to allocate
> some time and either pick up this PR or draft some ideas about how the
> functionality could be offered...)
>
I am still tracking this and would like to see it merged. Perhaps some of
the awkwardness comes from the implicit dependency on the client's Accessor
and async externals? For me that dependency is actually a plus e.g. loading
a glTF file over HTTP just "works."  Loading local files works for me too,
thanks to libcurl. While I could see the usefulness of offering something
more performant for local files, part of the appeal of this PR is that it
exercises several parts of Cesium Native and the client.

**Comment by kring** [comment]
I don't have a good answer, other than I haven't had a chance to really look at this yet. Really sorry about that.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @timoore! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by kring** [comment]
Thanks for your patience on this @timoore! It's embarassing how long it took me to review it. It looks great. I just merged in main, updated it for some of the latest changes, and added a test. Merging.

**Comment by javagl** [comment]
I'll schedule a test to see whether this fixes https://github.com/CesiumGS/cesium-native/issues/629 (and close that one, unless you already checked that)

**Comment by kring** [comment]
No I didn't try #629 specifically @javagl. Much appreciated if you give it a try and let me know.

**Comment by javagl** [comment]
It seems to be resolved, on the level where the issue is tracked. 

I tried it out in [`cesium-cpp`](https://github.com/javagl/cesium-cpp) where I already have a `FileAssetAccessor`,  `FileAssetResponse`, etc, and after a
```
  while (!future.isReady()) {
    externals.asyncSystem.dispatchMainThreadTasks();
  }
```
it returned the result without warnings. 

I could imagine that people would wish to have a function like
`GltfReaderResult result = GltfReader.justLoadThatGltf(uri);`
but that would have to be tracked in a dedicated issue.

**Comment by timoore** [comment]
Just to draw a line under my motivation for this PR, this is the glTF sample BarramundiFish loaded by vsgCs:
Screenshot from 2024-01-11 23-36-00

I'm using the same asset preparer pipeline and the same shaders for this single glTF file as I do for a 3D Tiles tileset, more or less. I'm happy to be able to test my asset preparer implementation on more exotic glTF content than I'm likely to find in 3D Tiles on e.g., Cesium ion.

**Pull request merged**
