### PR TITLE
Update TestSubtreeAvailability.cpp

### LINKED ISSUE #587: There seems to be a bug in TestSubtreeAvailability?
I think that bufferSize should be (1 + 4 + 16 + ...+ maxTiles) / 8.
For example,  for  3 levels tree, there are 21 tiles, bufferSize should be 3 NOT 2.

image

### PR DESCRIPTION
**Pull request by insar-dev**
fixed bug: used wrong tile number.
Fixes #587

### CODE REVIEW

**Comment by kring** [comment]
Thanks for the PR @insar-dev! It looks like we don't have a signed Contributor License Agreement from you yet. Can I bug you to do that so we can review and merge this? Details here:
https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla
Thanks!

**Comment by insar-dev** [comment]
@kring I have finished  signing CLA.

**Comment by kring** [comment]
Thanks @insar-dev! Looks like this isn't compiling at the moment:

```
C:\Users\travis\build\CesiumGS\cesium-native\Cesium3DTilesSelection\test\TestSubtreeAvailability.cpp(72): error C2065: 'maxSubtreeTiles': undeclared identifier [C:\Users\travis\build\CesiumGS\cesium-native\build\CesiumNativeTests\cesium-native-tests.vcxproj]
C:\Users\travis\build\CesiumGS\cesium-native\Cesium3DTilesSelection\test\TestSubtreeAvailability.cpp(365): warning C4244: 'argument': conversion from 'uint64_t' to 'int', possible loss of data [C:\Users\travis\build\CesiumGS\cesium-native\build\CesiumNativeTests\cesium-native-tests.vcxproj]
```

**Comment by kring** [comment]
Getting close, but there are still some compiler errors on GCC and Clang. Click the "Details button in the box below, click one of the failed builds, and scroll down until you see the errors.

**Comment by kring** [comment]
Thanks @insar-dev!

**Pull request merged**
