### PR TITLE
Fixed external tilesets not loading when frustum culling was disabled

### PR DESCRIPTION
**Pull request by nithinp7**
Fixes: #314

### CODE REVIEW

**Comment by kring** [comment]
This looks good, thanks @nithinp7! One idea to run past you, though: what do you think about using `std::numeric_limits<double>::infinity()` as the geometric error to mark a tile for unconditional refinement, rather than the bool? `glm::isinf` can be used to test for it. The advantage is less data in the Tile, which means (a little bit) less CPU cache thrashing during traversal. The disadvantage is perhaps it's a little less clear, but the `get/setUnconditionallyRefine` functions go a long way there.

**Comment by nithinp7** [comment]
@kring That's a good idea! I hadn't know that using infinity was idiomatic and safe, but it makes a ton of sense.

**Comment by nithinp7** [comment]
And by that last part, you mean keep the getter/setter there but change it so that it packs and unpacks infinity from the geometric error right?

**Comment by kring** [comment]
Yeah that's what I had in mind.

**Comment by kring** [comment]
I guess `setUnconditionallyRefine(false)` doesn't really make sense anymore, but I don't think it's needed, either. Just change it to `setToUnconditionallyRefine()` (parameterless) or somesuch.

**Comment by kring** [comment]
Thanks @nithinp7!

**Pull request merged**
